### ISSUE TITLE
Support for Laravel 5.1

### ISSUE THREAD

**Issue by karmendra** [lubusIN/laravel-decomposer#8] opened 2017-03-16 15:26 UTC
What version Supports for Laravel 5.1

**Comment by introwit** [comment] 2017-03-16 15:45
@karmendra The stable v1.0.1 that will be installed by default when you require the package.

**Comment by karmendra** [comment] 2017-03-16 15:54
Yes that's right.. my question is does any version of this package support l 5.1

**Comment by introwit** [comment] 2017-03-16 16:05
The stable v1.0.1 will work for you as I said in the comment above.

**Comment by karmendra** [comment] 2017-03-16 20:00
Well, I get following error when i try to install this package on Laravel 5.1

>  composer require lubusin/laravel-decomposer
Using version ^1.0 for lubusin/laravel-decomposer
./composer.json has been updated
php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Conclusion: remove laravel/framework v5.1.45
    - Conclusion: don't install laravel/framework v5.1.45
    - lubusin/laravel-decomposer v1.0 requires illuminate/database ~5.3 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.9].
    - lubusin/laravel-decomposer v1.0.1 requires illuminate/database ~5.3 -> satisfiable by illuminate/database[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.9].
    - don't install illuminate/database v5.3.0|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.3.16|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.3.23|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.3.4|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.4.0|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.4.13|don't install laravel/framework v5.1.45
    - don't install illuminate/database v5.4.9|don't install laravel/framework v5.1.45
    - Installation request for laravel/framework (locked at v5.1.45, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.45].
    - Installation request for lubusin/laravel-decomposer ^1.0 -> satisfiable by lubusin/laravel-decomposer[v1.0, v1.0.1].
Installation failed, reverting ./composer.json to its original content.

**Comment by introwit** [comment] 2017-03-17 13:26
@karmendra ah! Thanks for pointing that out. Will add the support for the LTS version on it's own branch. Will let you know once done.

**Comment by ryanvade** [comment] 2017-03-17 17:32
Related..support for 5.2?

**Comment by karmendra** [comment] 2017-03-17 17:40
@introwit Dhanyavaad :) Thanks

**Comment by introwit** [comment] 2017-03-17 18:14
@ryanvade will open up for 5.1 since it's the LTS release. Though it's coming to an end as 5.5 is near to release , will seek the possibilities of maintaining a branch for each 5.x version. That shouldn't be much as nothing extreme is being used. Will update you tomorrow on this after I give it a shot on my machine tomorrow morning :)

**Comment by ryanvade** [comment] 2017-03-18 15:14
@introwit awesome.  Let me know if I can be of assistance.

**Comment by introwit** [comment] 2017-03-19 09:23
@karmendra @ryanvade guys Decomposer is now compatible with Laravel 5.1 & 5.2 as well. So just `composer require lubusin/laravel-decomposer` and let me know if there are any other suggestions/issues/features you would like to point out. Also Ryan thank you for extending a hand to help, will surely let you know :) I created an issue on the composer repo itself to learn what's the best practice in such case and have followed their suggestions regarding semver & possible conflicts so all's good to go!

**Comment by introwit** [comment] 2017-03-19 09:37
@karmendra @ryanvade I have reopened the issue till you guys confirm it works for you now. If it works you can close the issue yourself or as I said let me know if still the problem persists.

**Comment by karmendra** [comment] 2017-03-19 10:29
It worked fine for me on Laravel 5.1, Thanks for your efforts in fixing this.
I had thoughts in my head that this package would tell me about laravel's .env file.
I thought running this will give me all the instances of env used in the code.

**Comment by introwit** [comment] 2017-03-19 11:44
@karmendra good thought but this is something on the other side of the line atleast for now. We need to draw a line somewhere afterall about what details to decompose & show. But as said in the roadmap, an update will be coming where you can add your personal checks as well, so that might do the trick for everyone :)

**Comment by ryanvade** [comment] 2017-03-19 21:32
@introwit Decompose is working just fine on Laravel 5.2.

**Comment by introwit** [comment] 2017-03-20 08:09
@ryanvade So since it's working for you guys as you confirmed, I am closing the issue. Thank you for the inputs & contributions :)

**Closed** 2017-03-20 08:10 UTC
